<a href="https://colab.research.google.com/github/guzweronika/DataScienceExercise/blob/numpy/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import the library](#0)
* [1.  np.all()](#1)
* [2.  np.all(__array__, axis=1)](#2)
* [3.  np.any()](#3)
* [4.  np.any(__array__, axis=0)](#4)
* [5.  np.isnan()](#5)
* [6.  np.allclose()](#6)
* [7.  ==](#7)
* [8.  >](#8)
* [9.  np.zeros()](#9)
* [10.  np.ones(), np.full()](#10)

### <a name='0'></a>Import the library

In [2]:
import numpy as np

np.__version__

'1.19.5'

### <a name='1'></a> EXERCISE 1.  np.all()
Check if all elements array $A,B,C, D$ give a logic value _True_ (USE a function _np.all()_).


In [ ]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
 
C = np.array([[True, False, False],
              [True, True, True]])
 Logic
D = np.array([0.1, 0.3])


print(f"Value of all arguments in arrays /nA: {np.all(A)}\nB: {np.all(B)}\nC: {np.all(C)}\nD: {np.all(D)}")

A: True
B: False
C: False
D: True


**NOTE** 

When is True in all() function?

True is when in my array I have all arguments True values.
 False value have a 0 number and False.

### <a name='2'></a> EXERCISE 2.  np.all(__array__, axis=1)
Chceck if all arguments of arrays $A, B, C$ give a logic value _True_ on axis with index value 1. (USE a function _np.all()_ with  _axis_)






In [ ]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
 
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
 
C = np.array([[True, False, False],
              [True, True, True]])

print(f"Value of a all arguments in arrays on axis with index \nA: {np.all(A, axis=1)}\nB: {np.all(B, axis=1)}\nC: {np.all(C, axis=1)}")

Value of a all arguments in arrays on axis with index 
A: [ True  True]
B: [ True False]
C: [False  True]


**NOTE**

The function __np.all()__ with argument __axis__ returns values True or False in a arrays. True value returns for a arguments where the all arguments in index axis (in rows) are True

### <a name='3'></a> EXERCISE 3. np.any()
Check if any argument of arrays $A, B, C, D$ give a logic value _True_. (USE  a function _np.any()_)



In [ ]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])
 
B = np.array([[0, 0, 0],
              [0, 1, 0]Logic])
 
C = np.array([[False, False, False],
              [True, False, False]])
 
D = np.array([[0.1, 0.0]])


print(f"Value of a any arguments in arrays \nA: {np.any(A)}\nB: {np.any(B)}\nC: {np.any(C)}\nD: {np.any(D)}")

Value of a any arguments in arrays 
A: False
B: True
C: True
D: True


**NOTE**

The function __np.any()__ returns values True or False in a arrays. True value returns for a arguments where the one of arguments is a False (for 0 or False)

### <a name='4'></a> EXERCISE 4. np.any(__array__, axis=0)
Check if any of elements of arrays $A, B, C D$ give a logic value_True_ in index axis 0. (USE _any()_ functions with a param _axis_)

In [ ]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

print(f"Value of a any arguments in arrays \nA: {np.any(A, axis=0)}\nB: {np.any(B, axis=0)}\nC: {np.any(C, axis=0)}\nD: {np.any(D, axis=0)}")

Value of a any arguments in arrays 
A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


**NOTE** 
The function np.any() with argument axis returns values True or False in a arrays. True value returns for a arguments where the one of arguments in index axis (in columns) are True (is not a 0 or False)

### <a name='5'></a> EXERCISE 5. _np.isnan()_
Check a array $A$ if are there lack of data (_np.nan_). (USE function _np.isnan()_)


In [3]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

print(f'Lack of data in A array\nA: {np.isnan(A)}')

Lack of data in A array
A: [[False False False  True]
 [False  True False False]]


**NOTE** np.isnan() function give a logical value True is a elements is a value np.nan



### <a name='6'></a> EXERCISE 6. _np.allclose()_
Check if the arrays $A, B$ are element-wise equal within a tolerance.
(USE function _np.allclose()_)


In [ ]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

print(f'Compare of arrays A and B {np.allclose(A, B)}')

 True


**NOTE** function _np.allclose()_ give a logic value True if elements-wise of two arrays are equal with tolerance

### <a name='7'></a> EXERCISE 7 _==_
Check if arrays $A, B$ are equal are element-wise equal. (USE function _==_)


In [ ]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

print(f'Compare each element in arrays A and B: {A==B}')

Compare each element in arrays A and B: [False False  True]


**NOTE** function _==_ give a logic value True for each array elemen if elements-wise of two arrays are equal without tolerance (is direct equal)

TIP: you can use np.equal()

### <a name='8'></a> EXERCISE 8 _>_
Check which elements-wise on array $A$ has a larger value as array $B$

In [ ]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

print(f'Elements in array A are larger than in array B:\n {A>B}')

Elements in array A are larger than in array B:
 [ True False False False]


**NOTE** Sign _>_ give a logic value for elements from array A greather as in array B

TIP: yoo can use function np.greather()

### <a name='9'></a> EXERCISE 9 _np.zeros()_
Create numpy array size 4x4 fill in zeros. Set data type in _int_. (USE function _np.zeros()_)


In [4]:
A = np.zeros((4,4), dtype='int')

print(f'Array A \n{A}')

print(f'\nType of elements array A: {type(A[1,1])}')

Array A 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Type of elements array A: <class 'numpy.int64'>


### <a name='10'></a> EXERCISE 10 _np.ones()_ _np.full()_
Create a numpy array in size _10x10_ fill in 255 numbers. Set data type in _float_. (USE function _np.ones()_ or _np.fill()_)


In [5]:
A_ones = np.ones((10,10)) * 255
print(f'Array A in ones function: \n{A_ones} \nwith array elements type: {type(A_ones[0,0])}\n\n')

B_full = np.full((10,10), 255, dtype=float)
print(f'Array B in full function:\n{B_full} \nwith array elements type: {type(B_full[0,0])}')

Array A in ones function: 
[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]] 
with array elements type: <class 'numpy.float64'>


Array B in full function:
[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255